# Experimental resource propagation logic.

# This file exists to create a package under which to load the experimental
# resource propagation logic bzl files.

package(default_visibility = [
    "//apple:__subpackages__",
])

licenses(["notice"])
