licenses(["notice"])

py_binary(
    name = "provisioning_profile_tool",
    srcs = ["provisioning_profile_tool.py"],
    # Used by the rule implementations, so it needs to be public.
    visibility = ["//visibility:public"],
)

# Consumed by bazel tests.
filegroup(
    name = "for_bazel_tests",
    testonly = 1,
    srcs = glob(["**"]),
    visibility = [
        "//tools:__pkg__",
    ],
)
