# Partials support.

# This file exists to create a package under which to load the processor
# partials support bzl files.

package(default_visibility = [
    "//apple/bundling/experimental/partials:__pkg__",
])

licenses(["notice"])
