"""Repository rules for exposing developer frameworks from the selected Xcode."""

load("@bazel_features//:features.bzl", "bazel_features")

_REPOSITORY_NAME = "local_developer_frameworks"
_FRAMEWORK_LINKER_INPUTS = {
    "XcodeKit": ["usr/lib/libXcodeExtension.a"],
}

def _framework_targets(framework_name, linker_inputs = []):
    linker_inputs_srcs = ", ".join([
        "\"{}\"".format(linker_input)
        for linker_input in linker_inputs
    ])
    return """\
filegroup(
    name = "{framework_name}_build_files",
    srcs = glob(["Frameworks/{framework_name}.framework/**"], allow_empty = False),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{framework_name}_runtime_files",
    srcs = glob([
        "Frameworks/{framework_name}.framework/Resources/**",
        "Frameworks/{framework_name}.framework/_CodeSignature/**",
        "Frameworks/{framework_name}.framework/Versions/*/Resources/**",
        "Frameworks/{framework_name}.framework/Versions/*/_CodeSignature/**",
    ], allow_empty = True),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{framework_name}_binary",
    srcs = glob([
        "Frameworks/{framework_name}.framework/{framework_name}",
        "Frameworks/{framework_name}.framework/Versions/*/{framework_name}",
    ], allow_empty = False),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{framework_name}_headers",
    srcs = glob([
        "Frameworks/{framework_name}.framework/Headers/**",
        "Frameworks/{framework_name}.framework/Versions/*/Headers/**",
    ], allow_empty = True),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{framework_name}_modulemaps",
    srcs = glob([
        "Frameworks/{framework_name}.framework/Modules/**",
        "Frameworks/{framework_name}.framework/Versions/*/Modules/**",
    ], allow_empty = True),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{framework_name}_linker_inputs",
    srcs = [{linker_inputs_srcs}],
    visibility = ["//visibility:public"],
)
""".format(
        framework_name = framework_name,
        linker_inputs_srcs = linker_inputs_srcs,
    )

def _developer_frameworks_repository_impl(repository_ctx):
    developer_dir = repository_ctx.os.environ.get("DEVELOPER_DIR")
    if not developer_dir:
        result = repository_ctx.execute(["/usr/bin/xcode-select", "-p"])
        if result.return_code:
            fail("Unable to resolve DEVELOPER_DIR. Pass --repo_env=DEVELOPER_DIR=... or ensure xcode-select is configured.")
        developer_dir = result.stdout.strip()

    frameworks_dir = repository_ctx.path(
        "{}/Library/Frameworks".format(developer_dir),
    )
    if not frameworks_dir.exists:
        fail("Developer frameworks directory does not exist: {}".format(frameworks_dir))

    repository_ctx.symlink(frameworks_dir, "Frameworks")
    repository_ctx.symlink(
        repository_ctx.path("{}/usr".format(developer_dir)),
        "usr",
    )

    framework_names = []
    for child in frameworks_dir.readdir():
        if child.basename.endswith(".framework") and child.is_dir:
            framework_names.append(child.basename[:-len(".framework")])

    framework_names = sorted(framework_names)
    build_file_contents = [
        "# Generated by rules_apple.",
        "",
    ]
    for framework_name in framework_names:
        build_file_contents.append(_framework_targets(
            framework_name,
            linker_inputs = _FRAMEWORK_LINKER_INPUTS.get(framework_name, []),
        ))

    repository_ctx.file(
        "BUILD.bazel",
        "\n".join(build_file_contents),
    )

local_developer_frameworks_repository = repository_rule(
    implementation = _developer_frameworks_repository_impl,
    environ = [
        "DEVELOPER_DIR",
        "XCODE_VERSION",
    ],
    doc = """
Declares an external repository exposing frameworks from
`$DEVELOPER_DIR/Library/Frameworks` and companion linker inputs from the
selected Xcode developer directory.
""",
)

def _developer_frameworks_repository_extension(module_ctx):
    local_developer_frameworks_repository(name = _REPOSITORY_NAME)

    metadata_kwargs = {}
    if bazel_features.external_deps.extension_metadata_has_reproducible:
        metadata_kwargs["reproducible"] = False

    return module_ctx.extension_metadata(**metadata_kwargs)

developer_frameworks_repository_extension = module_extension(
    implementation = _developer_frameworks_repository_extension,
    doc = """
Declares the `@{repo}` repository exposing frameworks from the selected Xcode
developer directory.
""".format(repo = _REPOSITORY_NAME),
)
