# Copyright 2026 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Starlark transition support for Apple rules.

This module makes the following distinctions around Apple CPU-adjacent values for clarity, based in
part on the language used for XCFramework library identifiers:

- `architecture`s or "arch"s represent the type of binary slice ("arm64", "x86_64").

- `environment`s represent a platform variant ("device", "sim"). These sometimes appear in the "cpu"
    keys out of necessity to distinguish new "cpu"s from an existing Apple "cpu" when a new
    Crosstool-provided toolchain is established.

- `platform_type`s represent the Apple OS being built for ("ios", "macos", "tvos", "visionos",
    "watchos").

- `cpu`s are keys to match a Crosstool-provided toolchain ("ios_sim_arm64", "ios_x86_64").
    Essentially it is a raw key that implicitly references the other three values for the purpose of
    getting the right Apple toolchain to build outputs with from the Apple Crosstool.
"""

load(
    "@build_bazel_rules_apple//apple/build_settings:build_settings.bzl",
    "build_settings_labels",
)
load(
    "@build_bazel_rules_apple//apple/internal:base_transition_support.bzl",
    "base_transition_support",
)
load(
    "@build_bazel_rules_apple//apple/internal:secure_features_support.bzl",
    "secure_features_support",
)

visibility([
    "@build_bazel_rules_apple//apple/...",
    "@build_bazel_rules_apple//test/...",
])

def _xcframework_split_attr_key(*, arch, environment, minimum_os_version, platform_type):
    """Return the split attribute key for this target within the XCFramework given linker options.

     Args:
        arch: The architecture of the target that was built. For example, `x86_64` or `arm64`.
        environment: The environment of the target that was built, which corresponds to the
            toolchain's target triple values as reported by `apple_support.link_multi_arch_binary`
            for environment. Typically `device` or `simulator`.
        minimum_os_version: A string representing the minimum OS version specified for this
            platform, represented as a dotted version number (for example, `"9.0"`).
        platform_type: The platform of the target that was built, which corresponds to the
            toolchain's target triple values as reported by `apple_support.link_multi_arch_binary`
            for platform. For example, `ios`, `macos`, `tvos`, `visionos` or `watchos`.

    Returns:
        A string representing the key for this target build found within the XCFramework with a
            format of <platform>_<arch>_<target_environment>, for example `darwin_arm64_device`.
    """

    # NOTE: This only passes "arch" to _cpu_string. To get the keys in the format XCFramework rules
    # expect, the environment is applied to the end of the key, much like it is for an XCFramework's
    # library identifiers as they are generated by Xcode.
    return base_transition_support.cpu_string(
        environment_arch = arch,
        minimum_os_version = minimum_os_version,
        platform_type = platform_type,
    ) + "_" + environment

def _resolved_environment_arch_for_arch(*, arch, environment, platform_type):
    if arch.startswith("arm64") and environment == "simulator" and platform_type != "watchos":
        return "sim_{}".format(arch)
    if arch.startswith("arm64") and environment == "device" and platform_type == "watchos":
        return "device_{}".format(arch)
    return arch

def _command_line_options_for_xcframework_platform(
        *,
        building_apple_bundle,
        features,
        force_bundle_outputs,
        minimum_os_version,
        name,
        platform_attr,
        platform_type,
        require_pointer_authentication_attribute,
        settings,
        target_environments):
    """Generates a dictionary of command line options keyed by 1:2+ transition for this platform.

    Args:
        building_apple_bundle: Indicates if the rule is building a bundle (rather than a
            standalone executable or library).
        features: A list of features to enable for this target.
        force_bundle_outputs: Indicates if the rule should always emit tree artifact outputs, which
            are effectively bundles that aren't enclosed within a zip file.
        minimum_os_version: A string representing the minimum OS version specified for this
            platform, represented as a dotted version number (for example, `"9.0"`).
        name: The name for the target that is being built.
        platform_attr: The attribute for the apple platform specifying in dictionary form which
            architectures to build for given a target environment as the key for this platform.
        platform_type: The Apple platform for which the rule should build its targets (`"ios"`,
            `"macos"`, `"tvos"`, `"visionos"`, or `"watchos"`).
        require_pointer_authentication_attribute: Indicates if the build requires pointer
            authentication to be enabled for arm64e builds.
        settings: A dictionary whose set of keys is defined by the inputs parameter, typically from
            the settings argument found on the implementation function of the current Starlark
            transition.
        target_environments: A list of strings representing target environments supported by the
            platform. Possible strings include "device" and "simulator".

    Returns:
        A dictionary of keys for each <platform>_<arch>_<target_environment> found with a
            corresponding dictionary of `"//command_line_option"`s as each key's value.
    """
    output_dictionary = {}
    for target_environment in target_environments:
        if not platform_attr.get(target_environment):
            continue
        sorted_target_archs = sorted(platform_attr[target_environment])
        for arch in sorted_target_archs:
            arch_features = list(features)
            if arch == "arm64e" and "pointer_authentication" not in arch_features:
                if require_pointer_authentication_attribute:
                    # This is the one place where we explicitly error if pointer_authentication
                    # isn't requested alongside arm64e, as other instances (i.e. from an ios_release
                    # config) should be silently dropped and only escalated as an error in single
                    # arch builds.
                    fail("""
ERROR: Target "{target}" is configured to build for arm64e, but the target does not declare \
"pointer_authentication" in its `secure_features` attribute. This is required to use arm64e for \
apps shipping with Xcode 26 and later.

Please add "pointer_authentication" to the `secure_features` attribute of target "{target}" to \
allow it to build for arm64e with the required Apple capabilities for pointer authentication.
""".format(target = str(name)))

                # In the meantime, help onboard XCFramework rule users to pointer_authentication by
                # adding the feature if it is missing and they have not yet explicitly enabled
                # pointer_authentication.
                arch_features.append("pointer_authentication")

            resolved_environment_arch = _resolved_environment_arch_for_arch(
                arch = arch,
                environment = target_environment,
                platform_type = platform_type,
            )

            found_cpu = {
                _xcframework_split_attr_key(
                    arch = arch,
                    environment = target_environment,
                    minimum_os_version = minimum_os_version,
                    platform_type = platform_type,
                ): base_transition_support.command_line_options(
                    building_apple_bundle = building_apple_bundle,
                    environment_arch = resolved_environment_arch,
                    features = arch_features,
                    force_bundle_outputs = force_bundle_outputs,
                    minimum_os_version = minimum_os_version,
                    platform_type = platform_type,
                    settings = settings,
                ),
            }
            output_dictionary |= found_cpu

    return output_dictionary

def _xcframework_base_transition_impl(settings, attr):
    """Rule transition for XCFramework rules producing SDK-adjacent artifacts."""

    requested_features = secure_features_support.crosstool_features_from_secure_features(
        features = settings["//command_line_option:features"],
        name = attr.name,
        secure_features = attr.secure_features,
    )

    # For safety, explicitly lean on darwin_arm64 with no incoming minimum_os_version to avoid
    # incoming settings meant for other platforms overriding the settings for the xcframework rule's
    # underlying actions, and allow for toolchain resolution in the future.
    return base_transition_support.command_line_options(
        building_apple_bundle = False,
        environment_arch = "arm64",
        features = requested_features,
        force_bundle_outputs = False,
        minimum_os_version = None,
        platform_type = "macos",
        settings = settings,
    )

_xcframework_base_transition = transition(
    implementation = _xcframework_base_transition_impl,
    inputs = base_transition_support.apple_rule_common_transition_inputs,
    outputs = base_transition_support.apple_rule_base_transition_outputs,
)

def _xcframework_split_transition_impl(settings, attr):
    """Starlark 1:2+ transition for generation of multiple frameworks for the current target."""
    output_dictionary = {}

    requested_features = secure_features_support.crosstool_features_from_secure_features(
        features = settings["//command_line_option:features"],
        name = attr.name,
        secure_features = attr.secure_features,
    )
    require_pointer_authentication_attribute = (
        settings[build_settings_labels.require_pointer_authentication_attribute]
    )

    for platform_type in ["ios", "tvos", "watchos", "visionos", "macos"]:
        if not hasattr(attr, platform_type):
            continue
        target_environments = ["device"]
        if platform_type != "macos":
            target_environments.append("simulator")

        command_line_options = _command_line_options_for_xcframework_platform(
            building_apple_bundle = getattr(attr, "_building_apple_bundle", True),
            features = requested_features,
            force_bundle_outputs = getattr(attr, "_force_bundle_outputs", False),
            minimum_os_version = attr.minimum_os_versions.get(platform_type),
            name = attr.name,
            platform_attr = getattr(attr, platform_type),
            platform_type = platform_type,
            require_pointer_authentication_attribute = require_pointer_authentication_attribute,
            settings = settings,
            target_environments = sorted(target_environments),
        )
        output_dictionary |= command_line_options
    return output_dictionary

_xcframework_split_transition = transition(
    implementation = _xcframework_split_transition_impl,
    inputs = base_transition_support.apple_rule_common_transition_inputs,
    outputs = base_transition_support.apple_rule_base_transition_outputs,
)

xcframework_transition_support = struct(
    xcframework_base_transition = _xcframework_base_transition,
    xcframework_split_attr_key = _xcframework_split_attr_key,
    xcframework_split_transition = _xcframework_split_transition,
)
