licenses(["notice"])

cc_binary(
    name = "containerpathtool",
    srcs = ["containerpathtool.c"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_libimobiledevice_libimobiledevice//:libimobiledevice",
    ]
)
