py_binary(
    name = "write_license_text",
    srcs = ["write_license_text.py"],
    python_version = "PY3",
    # Used by the rule implementations, so it needs to be public; but
    # should be considered an implementation detail of the rules and
    # not used by other things.
    visibility = ["//visibility:public"],
)
