# Copyright 2026 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Actions for communicating with ExtensionKit using exutil."""

load("@build_bazel_apple_support//lib:apple_support.bzl", "apple_support")
load("@build_bazel_rules_apple//apple/internal:intermediates.bzl", "intermediates")
load(
    "@build_bazel_rules_apple//apple/internal:resource_actions.bzl",
    "resource_actions",
)
load(
    "@build_bazel_rules_apple//apple/internal:shared_environment.bzl",
    "shared_environment",
)
load(
    "@build_bazel_rules_apple//apple/internal/utils:platform_defaults.bzl",
    "platform_defaults",
)
load(
    "@build_bazel_rules_apple//apple/internal/utils:xcode_support.bzl",
    "xcode_support",
)

visibility(["@build_bazel_rules_apple//apple/internal/..."])

def extract_extension_points(
        *,
        actions,
        apple_mac_toolchain_info,
        apple_xplat_toolchain_info,
        bundle_id,
        extension_point_inputs,
        label,
        mac_exec_group,
        platform_prerequisites,
        xplat_exec_group):
    """Generates .appexpt files for each associated swiftconstvalues file.

    Args:
        actions: The actions provider from `ctx.actions`.
        apple_mac_toolchain_info: `struct` of Apple tools from the shared Apple toolchain.
        apple_xplat_toolchain_info: `struct` of xplat tools from the shared Apple toolchain.
        bundle_id: The bundle identifier.
        extension_point_inputs: A list of AppExtensionPointInfo structs.
        label: The label of the target being analyzed.
        mac_exec_group: The execution group for Mac tools.
        platform_prerequisites: The prerequisites related to the Apple platform.
        xplat_exec_group: The execution group for cross-platform tools.

    Returns:
        A list of `.appexpt` File objects generated by exutil.
    """

    xcode_version_config = platform_prerequisites.xcode_version_config

    outputs = []

    for input in extension_point_inputs:
        module_name = input.module_name
        unique_files = {}
        for f in input.swiftconstvalues_files.to_list():
            if f.short_path not in unique_files:
                unique_files[f.short_path] = f

        valid_swiftconstvalues = []
        for swiftconstvalues_file in unique_files.values():
            if swiftconstvalues_file.basename.endswith(".swiftconstvalues"):
                valid_swiftconstvalues.append(swiftconstvalues_file)

        if not valid_swiftconstvalues:
            continue

        output_appexpt = intermediates.file(
            actions = actions,
            file_name = "%s.appexpt" % module_name,
            output_discriminator = None,
            target_name = label.name,
        )

        tmp_appexpt = intermediates.file(
            actions = actions,
            file_name = "%s.tmp.appexpt" % module_name,
            output_discriminator = None,
            target_name = label.name,
        )

        # Update output arg
        args = actions.args()
        args.add("exutil")
        args.add("extract-extension-points")
        args.add("--module-name", module_name)
        args.add("--toolchain-dir", "{xcode_path}/Toolchains/XcodeDefault.xctoolchain".format(
            xcode_path = apple_support.path_placeholders.xcode(),
        ))
        args.add("--sdk-root", apple_support.path_placeholders.sdkroot())
        args.add(
            "--xcode-version",
            xcode_support.xcode_build_version(xcode_version_config = xcode_version_config),
        )
        args.add("--platform-family", platform_defaults.platform_family(
            platform_prerequisites.platform_type,
        ))
        args.add("--deployment-target", platform_prerequisites.minimum_os)
        args.add("--bundle-identifier", bundle_id)
        args.add("--output", tmp_appexpt.path)
        args.add_all(valid_swiftconstvalues)

        apple_support.run(
            actions = actions,
            apple_platform_info = platform_prerequisites.apple_platform_info,
            arguments = [args],
            env = shared_environment.default_env,
            executable = apple_mac_toolchain_info.xctoolrunner_alternative,
            exec_group = mac_exec_group,
            inputs = valid_swiftconstvalues,
            mnemonic = "ExtensionPointExtractor",
            outputs = [tmp_appexpt],
            xcode_config = xcode_version_config,
            xcode_path_resolve_level = apple_support.xcode_path_resolve_level.args,
        )

        # Convert to XML plist
        control = struct(
            binary = False,
            output = output_appexpt.path,
            plists = [tmp_appexpt.path],
            target = str(label),
        )
        resource_actions.plisttool_action(
            actions = actions,
            apple_mac_toolchain_info = apple_mac_toolchain_info,
            apple_xplat_toolchain_info = apple_xplat_toolchain_info,
            control = control,
            inputs = [tmp_appexpt],
            mac_exec_group = mac_exec_group,
            mnemonic = "ExtensionPointFormatXML",
            outputs = [output_appexpt],
            platform_prerequisites = platform_prerequisites,
            xplat_exec_group = xplat_exec_group,
        )
        outputs.append(output_appexpt)

    return outputs

def generate_appextension_plist(
        *,
        actions,
        apple_mac_toolchain_info,
        bundle_id,
        label,
        mac_exec_group,
        module_name,
        platform_prerequisites,
        swiftconstvalues_files):
    """Generates the EXAppExtensionAttributes Info.plist fragment for an extension.

    Args:
        actions: The actions provider from `ctx.actions`.
        apple_mac_toolchain_info: `struct` of Apple tools from the shared Apple toolchain.
        bundle_id: The bundle identifier of the extension.
        label: The label of the target being analyzed.
        mac_exec_group: The execution group for Mac tools.
        module_name: The module name of the Swift executable.
        platform_prerequisites: The prerequisites related to the Apple platform.
        swiftconstvalues_files: A depset or list of `.swiftconstvalues` File objects.

    Returns:
        A File object representing the generated EXAppExtensionAttributes.plist.
    """

    xcode_version_config = platform_prerequisites.xcode_version_config

    output_plist = intermediates.file(
        actions = actions,
        file_name = "EXAppExtensionAttributes.plist",
        output_discriminator = None,
        target_name = label.name,
    )

    constvalues_files = swiftconstvalues_files

    main_module = module_name

    args = actions.args()
    args.add("exutil")
    args.add("generate-appextension-plist")
    args.add("--module-name", main_module)
    args.add("--toolchain-dir", "{xcode_path}/Toolchains/XcodeDefault.xctoolchain".format(
        xcode_path = apple_support.path_placeholders.xcode(),
    ))
    args.add("--sdk-root", apple_support.path_placeholders.sdkroot())
    args.add(
        "--xcode-version",
        xcode_support.xcode_build_version(xcode_version_config = xcode_version_config),
    )
    args.add("--platform-family", platform_defaults.platform_family(
        platform_prerequisites.platform_type,
    ))
    args.add("--deployment-target", platform_prerequisites.minimum_os)
    args.add("--bundle-identifier", bundle_id)
    args.add("--output", output_plist.path)
    args.add_all(constvalues_files)

    apple_support.run(
        actions = actions,
        apple_platform_info = platform_prerequisites.apple_platform_info,
        arguments = [args],
        env = shared_environment.default_env,
        executable = apple_mac_toolchain_info.xctoolrunner_alternative,
        exec_group = mac_exec_group,
        inputs = constvalues_files,
        mnemonic = "AppExtensionPlistGenerator",
        outputs = [output_plist],
        xcode_config = xcode_version_config,
        xcode_path_resolve_level = apple_support.xcode_path_resolve_level.args,
    )
    return output_plist
