package(default_visibility = ["//visibility:public"])

licenses(["notice"])

filegroup(
    name = "integration_testing_profiles",
    srcs = [
        "integration_testing_ios.mobileprovision",
        "integration_testing_tvos.mobileprovision",
    ],
)
