# Partials.

# This file exists to create a package under which to load the processor
# partials bzl files.

package(default_visibility = [
    "//apple/bundling/experimental:__pkg__",
])

licenses(["notice"])
