package(default_visibility = ["//visibility:public"])

licenses(["notice"])

filegroup(
    name = "dummy_runner",
    srcs = [
        "BUILD",
        "dummy_test_runner.bzl",
        "dummy_test_runner.template",
    ],
)
