name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The new version to tag, ex: 1.0.5'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        run: |
          set -euo pipefail

          COPYFILE_DISABLE=1 tar czvf "rules_apple.$TAG.tar.gz" ./*
          ./.github/generate-notes.sh "$TAG" | tee notes.md

          # Add generated API docs to the release
          # See https://github.com/bazelbuild/bazel-central-registry/blob/main/docs/stardoc.md
          docs="$(mktemp -d)"; targets="$(mktemp)"
          bazel --output_base="$docs" query --output=label --output_file="$targets" 'kind("starlark_doc_extract rule", //...)'
          bazel --output_base="$docs" build --target_pattern_file="$targets"
          tar --create --auto-compress \
              --directory "$(bazel --output_base="$docs" info bazel-bin)" \
              --file "rules_apple.$TAG.docs.tar.gz" .

          gh release create "$TAG" --title "$TAG" --target "$GITHUB_REF_NAME" --notes-file notes.md "rules_apple.$TAG.tar.gz" "rules_apple.$TAG.docs.tar.gz"
        env:
          TAG: ${{ inputs.tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: create-release
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.0.0
    with:
      tag_name: ${{ inputs.tag }}
      registry_fork: bazelbuild/bazel-central-registry
      draft: false
      # TODO: Enable attestations once supported
      # https://github.com/bazel-contrib/publish-to-bcr/issues/342
      attest: false
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
    permissions:
      attestations: write
      contents: write
      id-token: write
