name: CI
"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Every day at 11:03 UTC.
    - cron: '3 11 * * *'

concurrency: # Only allow a single build/test run at a time for a PR.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        bazel_version:
          - "7.x"
          - "latest"
          - "4c2d91e762ab6e492853b021408129dd93fb5904" # TODO: Switch back to last_green once get_cpu has been removed
          # - "rolling"
          # - "last_green"

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: USE_BAZEL_VERSION=${{ matrix.bazel_version }} bazelisk test //... --config=ci
