name: CI
"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Every day at 11:03 UTC.
    - cron: '3 11 * * *'

jobs:
  test:
    strategy:
      matrix:
        bazel_version: ["7.x", "latest", "rolling", "last_green"]

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: USE_BAZEL_VERSION=${{ matrix.bazel_version }} bazelisk test //...
